//! patchi_wani_engine — Rust game engine
//!
//! Exposed as a C ABI shared library called from Flutter via dart:ffi.
//! All public functions use `extern "C" #[no_mangle]`.

use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_float, c_int};
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

// ─────────────────────────────────────────────
//  GameRule — configuration generated by the Scratch block editor
// ─────────────────────────────────────────────
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GameRule {
    /// Game duration in seconds
    pub duration_secs: u32,
    /// How long the target stays visible (milliseconds)
    pub appear_ms: u32,
    /// Difficulty threshold 1 — target shrinks above this score
    pub threshold_1: u32,
    /// Difficulty threshold 2 — target shrinks further above this score
    pub threshold_2: u32,
    /// Target sizes for each difficulty level [easy, normal, hard] in dp
    pub target_sizes: [f32; 3],
}

impl Default for GameRule {
    fn default() -> Self {
        Self {
            duration_secs: 60,
            appear_ms:     1500,
            threshold_1:   10,
            threshold_2:   20,
            target_sizes:  [96.0, 68.0, 50.0],
        }
    }
}

// ─────────────────────────────────────────────
//  GameState — internal game state
// ─────────────────────────────────────────────
#[derive(Debug, Clone, PartialEq)]
pub enum Phase {
    Idle,
    Playing,
    GameOver,
}

#[derive(Debug)]
pub struct GameState {
    pub phase:     Phase,
    pub score:     u32,
    pub time_left: u32,  // remaining seconds
    pub rule:      GameRule,
}

impl GameState {
    fn new(rule: GameRule) -> Self {
        Self {
            phase:     Phase::Idle,
            score:     0,
            time_left: rule.duration_secs,
            rule,
        }
    }

    /// Returns the target size in dp for the current score
    pub fn current_target_size(&self) -> f32 {
        if self.score < self.rule.threshold_1 {
            self.rule.target_sizes[0]
        } else if self.score < self.rule.threshold_2 {
            self.rule.target_sizes[1]
        } else {
            self.rule.target_sizes[2]
        }
    }

    /// Returns difficulty level: 0 = easy, 1 = normal, 2 = hard
    pub fn difficulty_level(&self) -> u8 {
        if self.score < self.rule.threshold_1 {
            0
        } else if self.score < self.rule.threshold_2 {
            1
        } else {
            2
        }
    }
}

// ─────────────────────────────────────────────
//  Global state (Mutex-protected)
// ─────────────────────────────────────────────
static STATE: Mutex<Option<GameState>> = Mutex::new(None);

fn with_state<F, T>(f: F) -> T
where
    F: FnOnce(&mut GameState) -> T,
{
    let mut guard = STATE.lock().expect("mutex poisoned");
    let state = guard.as_mut().expect("engine not initialised — call engine_init first");
    f(state)
}

// ─────────────────────────────────────────────
//  C ABI exports
// ─────────────────────────────────────────────

/// Initialise the engine.
/// `rule_json`: JSON string of GameRule (pass NULL to use defaults).
/// Returns 0 on success, -1 on JSON parse error.
///
/// # Safety
/// `rule_json` must be a valid null-terminated C string, or NULL.
#[no_mangle]
pub unsafe extern "C" fn engine_init(rule_json: *const c_char) -> c_int {
    let rule = if rule_json.is_null() {
        GameRule::default()
    } else {
        let cstr = unsafe { CStr::from_ptr(rule_json) };
        match serde_json::from_str::<GameRule>(cstr.to_str().unwrap_or("")) {
            Ok(r) => r,
            Err(_) => return -1,
        }
    };

    let mut guard = STATE.lock().expect("mutex poisoned");
    *guard = Some(GameState::new(rule));
    0
}

/// Start the game (Idle → Playing).
#[no_mangle]
pub extern "C" fn engine_start() {
    with_state(|s| {
        s.phase     = Phase::Playing;
        s.score     = 0;
        s.time_left = s.rule.duration_secs;
    });
}

/// Advance the timer by one second. Call from Flutter's Timer.periodic(1s).
/// Returns remaining seconds (0 means game over).
#[no_mangle]
pub extern "C" fn engine_tick() -> c_int {
    with_state(|s| {
        if s.phase != Phase::Playing {
            return s.time_left as c_int;
        }
        if s.time_left > 0 {
            s.time_left -= 1;
        }
        if s.time_left == 0 {
            s.phase = Phase::GameOver;
        }
        s.time_left as c_int
    })
}

/// Call when the player taps the target.
/// Returns the updated score, or -1 if the game is not in Playing state.
#[no_mangle]
pub extern "C" fn engine_on_hit() -> c_int {
    with_state(|s| {
        if s.phase != Phase::Playing {
            return -1;
        }
        s.score += 1;
        s.score as c_int
    })
}

/// Returns the current score.
#[no_mangle]
pub extern "C" fn engine_get_score() -> c_int {
    with_state(|s| s.score as c_int)
}

/// Returns the remaining time in seconds.
#[no_mangle]
pub extern "C" fn engine_get_time_left() -> c_int {
    with_state(|s| s.time_left as c_int)
}

/// Returns the current phase: 0 = Idle, 1 = Playing, 2 = GameOver.
#[no_mangle]
pub extern "C" fn engine_get_phase() -> c_int {
    with_state(|s| match s.phase {
        Phase::Idle     => 0,
        Phase::Playing  => 1,
        Phase::GameOver => 2,
    })
}

/// Returns the target size in dp for the current difficulty level.
#[no_mangle]
pub extern "C" fn engine_get_target_size() -> c_float {
    with_state(|s| s.current_target_size())
}

/// Returns the difficulty level: 0 = easy, 1 = normal, 2 = hard.
#[no_mangle]
pub extern "C" fn engine_get_difficulty() -> c_int {
    with_state(|s| s.difficulty_level() as c_int)
}

/// Returns the current GameRule as a JSON string.
/// The caller must free the pointer with `engine_free_string`.
#[no_mangle]
pub extern "C" fn engine_get_rule_json() -> *mut c_char {
    with_state(|s| {
        let json = serde_json::to_string(&s.rule).unwrap_or_default();
        CString::new(json).unwrap().into_raw()
    })
}

/// Frees a pointer returned by `engine_get_rule_json`.
///
/// # Safety
/// `ptr` must be a pointer previously returned by `engine_get_rule_json`, or NULL.
#[no_mangle]
pub unsafe extern "C" fn engine_free_string(ptr: *mut c_char) {
    if !ptr.is_null() {
        unsafe { drop(CString::from_raw(ptr)) };
    }
}

// ─────────────────────────────────────────────
//  Unit tests
// ─────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex;

    // Serialize tests that share the global engine singleton.
    static TEST_LOCK: Mutex<()> = Mutex::new(());

    fn setup() -> std::sync::MutexGuard<'static, ()> {
        let guard = TEST_LOCK.lock().unwrap();
        let rule = GameRule::default();
        let json = serde_json::to_string(&rule).unwrap();
        let cstr = CString::new(json).unwrap();
        assert_eq!(unsafe { engine_init(cstr.as_ptr()) }, 0);
        guard
    }

    #[test]
    fn test_initial_state() {
        let _guard = setup();
        assert_eq!(engine_get_phase(), 0);  // Idle
        assert_eq!(engine_get_score(), 0);
        assert_eq!(engine_get_time_left(), 60);
    }

    #[test]
    fn test_game_flow() {
        let _guard = setup();
        engine_start();
        assert_eq!(engine_get_phase(), 1);  // Playing

        // hits increase score
        assert_eq!(engine_on_hit(), 1);
        assert_eq!(engine_on_hit(), 2);
        assert_eq!(engine_get_score(), 2);

        // 60 ticks → game over
        for _ in 0..60 {
            engine_tick();
        }
        assert_eq!(engine_get_phase(), 2);  // GameOver
    }

    #[test]
    fn test_difficulty_scaling() {
        let _guard = setup();
        engine_start();

        // easy: score 0–9
        assert_eq!(engine_get_difficulty(), 0);
        assert!((engine_get_target_size() - 96.0).abs() < 0.1);

        // normal: score 10–19
        for _ in 0..10 { engine_on_hit(); }
        assert_eq!(engine_get_difficulty(), 1);
        assert!((engine_get_target_size() - 68.0).abs() < 0.1);

        // hard: score 20+
        for _ in 0..10 { engine_on_hit(); }
        assert_eq!(engine_get_difficulty(), 2);
        assert!((engine_get_target_size() - 50.0).abs() < 0.1);
    }

    #[test]
    fn test_rule_json_roundtrip() {
        let _guard = setup();
        let ptr = engine_get_rule_json();
        assert!(!ptr.is_null());
        let json = unsafe { CStr::from_ptr(ptr).to_str().unwrap().to_owned() };
        unsafe { engine_free_string(ptr) };
        let rule: GameRule = serde_json::from_str(&json).unwrap();
        assert_eq!(rule.duration_secs, 60);
    }
}
